name: on-push
run-name: on push to main

on:
  push:
    branches:
      - main

  # run if user manually requests it
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  make-paper-thumbnail:
    uses: ./.github/workflows/make-paper-thumbnail.yaml

  update-citations:
    # skip first run because nothing enabled or setup yet
    if: github.run_number != 1
    needs: make-paper-thumbnail
    uses: ./.github/workflows/update-citations.yaml

  build-site:
    needs: [update-citations, make-paper-thumbnail]
    uses: ./.github/workflows/build-site.yaml
